# Generated by Django 3.2.5 on 2021-08-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Houses',
        ),
        migrations.RenameModel(
            old_name='Wizard',
            new_name='Wizards',
        ),
    ]
